server:
  servlet:
    context-path: /projects
  port: 8078

spring:
  application:
    name: projects

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://database:5432/capstoneprojectsdb
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    properties.hibernate.format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}



