
spring:
  application:
    name: projects

  profiles:
    active: dev
  cloud:
    kubernetes:
      enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}

server:
  servlet:
    context-path: /projects
