springdoc:
  api-docs:
    path: '/api-docs'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/capstoneprojectsdb
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    properties.hibernate.format_sql: true