eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://database:5432/capstoneprojectsdb
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    properties.hibernate.format_sql: true